### PR TITLE
redesigned schema including timestamp and added query docs

### PR DESCRIPTION
**Pull request by jchen0506**

### CODE REVIEW

**Comment by jchen0506** [comment]
@Vasanarul @jensenchelese @orlando-apps Can you guys review this for me. There is not much in casssandra seeding file since I did most of them in cqlsh shell. I also included a query result readme file

**Comment by orlando-apps** [comment]
No comments. This looks good.

**Comment by Vasanarul** [comment]
The code looks great! Only minor thing I found was making Cassandra singular or adding a \' on the console log of line 13 of db/cassconnection.js, but the queries and variable naming are both really well done.

**Comment by jchen0506** [comment]
> The code looks great! Only minor thing I found was making Cassandra singular or adding a ' on the console log of line 13 of db/cassconnection.js, but the queries and variable naming are both really well done.

Nice catch! Will change it

**Pull request merged**
